#! /bin/sh

bspc monitor DP-2 -d 1 2 3 4 5 
bspc monitor HDMI-0 -d 6 7 8 9 10
bspc monitor DP-4 -d 11 12 13 14 15

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc config focused_border_color    "#a3be8c"
# bspc config normal_border_color     "#bf616a"
bspc config urgent_border_color     "#ebcb8b"
bspc config presel_border_color     "#a3be8c"
bspc config presel_feedback_color   "#b48ead"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a yesplaymusic desktop='^0'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


$HOME/.config/polybar/launch.sh
# $HOME/.screenlayout/display.sh
# gentoo-pipewire-launcher &
# pgrep -x sxhkd > /dev/null || sxhkd &
# pgrep -x clipit > /dev/null || clipit &
# pgrep -x fcitx > /dev/null || fcitx &
# pgrep -x flameshot > /dev/null || flameshot &
# xsetroot -cursor_name left_ptr
# nitrogen --restore &
# xset dpms 600 600 600
